facebook:
  app_id: APP_ID
  app_secret: APP_SECRET
  scope: publish_stream,offline_access,email
twitter:
  consumer_key: CONSUMER_KEY
  consumer_secret: CONSUMER_SECRET
linked_in:
  consumer_key: CONSUMER_KEY
  consumer_secret: CONSUMER_SECRET
