# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 1) do

  create_table "contacts", :force => true do |t|
    t.column "first_name",     :string,  :default => "", :null => false
    t.column "last_name",      :string,  :default => "", :null => false
    t.column "phone_number",   :string
    t.column "fax_number",     :string
    t.column "email_address",  :string
    t.column "web_address",    :string
    t.column "department",     :string
    t.column "continent_id",   :integer,                 :null => false
    t.column "region_id",      :integer,                 :null => false
    t.column "city_id",        :integer,                 :null => false
    t.column "address_line_1", :string
    t.column "address_line_2", :string
    t.column "postal_code",    :string
  end

  create_table "milestone_histories", :force => true do |t|
    t.column "milestone_id", :integer
    t.column "created_at",   :datetime
    t.column "reason",       :text
    t.column "category",     :string
    t.column "description",  :text
    t.column "start",        :date
    t.column "end",          :date
    t.column "status_id",    :integer
  end

  create_table "milestones", :force => true do |t|
    t.column "category",    :string,  :default => "", :null => false
    t.column "description", :text,    :default => "", :null => false
    t.column "start",       :date,                    :null => false
    t.column "end",         :date,                    :null => false
    t.column "status_id",   :integer,                 :null => false
  end

  create_table "project_histories", :force => true do |t|
    t.column "project_id",               :integer,  :null => false
    t.column "date",                     :datetime
    t.column "cost",                     :float
    t.column "dollars_spent",            :float
    t.column "expected_completion_date", :datetime
    t.column "start_date",               :datetime
    t.column "end_date",                 :datetime
    t.column "user_id",                  :integer
    t.column "status_id",                :integer
  end

  create_table "projects", :force => true do |t|
    t.column "program_id",               :integer
    t.column "category_id",              :integer
    t.column "name",                     :string,   :default => "", :null => false
    t.column "description",              :text
    t.column "cost",                     :float
    t.column "dollars_spent",            :float
    t.column "expected_completion_date", :datetime
    t.column "start_date",               :datetime
    t.column "end_date",                 :datetime
    t.column "status_id",                :integer
    t.column "contact_id",               :integer
    t.column "location_id",              :integer
  end

  create_table "statuses", :force => true do |t|
    t.column "category",    :string, :default => "", :null => false
    t.column "description", :text,   :default => "", :null => false
  end

end
