# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 3) do

  create_table "project_histories", :force => true do |t|
    t.column "project_id",               :integer,  :null => false
    t.column "date",                     :datetime
    t.column "cost",                     :float
    t.column "dollars_spent",            :float
    t.column "expected_completion_date", :datetime
    t.column "start_date",               :datetime
    t.column "end_date",                 :datetime
    t.column "user_id",                  :integer
    t.column "status_id",                :integer
  end

  create_table "projects", :force => true do |t|
    t.column "program_id",               :integer
    t.column "category_id",              :integer
    t.column "name",                     :string,   :default => "", :null => false
    t.column "description",              :text
    t.column "cost",                     :float
    t.column "dollars_spent",            :float
    t.column "expected_completion_date", :datetime
    t.column "start_date",               :datetime
    t.column "end_date",                 :datetime
    t.column "status_id",                :integer
    t.column "contact_id",               :integer
    t.column "location_id",              :integer
  end

end
